### PR TITLE
Add report transaction API support

### PR DESCRIPTION
**Pull request by oalders**
This adds support for the Report Transaction minFraud API. As far as naming goes, the new functionality didn't seem like a good fit for an assessment, so I've made some naming choices. I can certainly make any changes you'd like.

### CODE REVIEW

**Comment by kushniryb** [comment]
Thank you so much @oalder, it looks perfect! And thanks for grammatical tweaks, much appreciated ❤️

I'll merge it first thing in the morning.

By the way, am I correct to assume that you're working with @horgh? Would you guys like to take care of this repository moving forward? I don't have a lot of time lately to take care of it and I can see that you know what you're doing code-wise as well as keeping an eye for the MaxMind updates. 

What would you say? Lemme know what you think :)

**Comment by oalders** [comment]
@kushniryb thanks very much for your review and your kind words. ❤️ 

I do work with @horgh. We've had a conversation about it and we would certainly like to take you up on your offer. I believe he or @oschwald will reach out to you about MaxMind taking on maintenance of the code. Thanks for all of your work on this -- it's a very valuable tool!

**Comment by horgh** [comment]
Hi @kushniryb! Thank you for the offer! We're definitely interested in helping maintain the project, either fully or as you prefer. We certainly appreciate your efforts!

How would you like it to work? Would you want to add a few of us as collaborators? Or transfer it to our org?

Also, would you want to add some of us to the gem so we could do releases as well?

Thank you!

**Comment by kushniryb** [comment]
@horgh @oalders 

Thank you for your quick response and for the willingness to continue maintaining and developing this gem, it means a lot! 

I was thinking about transferring the repository to one of you and perhaps you could take care of the rest? Would it work or am I missing something?

**Comment by horgh** [comment]
Yes, I think that'd work! You could transfer it to me if you like.

It'd also be good if we could get added to it on rubygems.org too - my user on there is wstorey. I think you can use the `gem owner` command to add owners there. My understanding is that is a separate thing.

Thank you!

**Comment by oalders** [comment]
Thanks for the merge @kushniryb! 🎉

**Comment by kushniryb** [comment]
@horgh 

Added you to the owners on rubygems.org
Transferring the repo, thanks a lot guys :)

**Comment by kushniryb** [comment]
@horgh Could you please remove your fork first? Can't transfer the repository otherwise

**Comment by horgh** [comment]
Oops, sorry! I just did. Thank you!

**Pull request merged**
