### PR TITLE
Add response classes

### PR DESCRIPTION
**Pull request by horgh**
This creates classes for the various response types and attributes. It is related to #14.

I've tried to maintain backwards compatibility as much as possible, in particular ensuring the same attributes that could have been available before are still present.

It also drops the dependency on hashie (#7).

However it adds a new dependency on [maxmind-geoip2](https://github.com/maxmind/GeoIP2-ruby). This is because we can use the classes related to the GeoIP2 Insights response.

One thing I realised as I was wrapping this up is that maxmind-geoip2 depends on Ruby 2.4+ currently, so I bumped the required version to that. What do you think about this? That gem dropped support for older Ruby versions as 2.3 and older are now unsupported/end of life. It's possible we could do something about this to support older versions though.

Thank you!

### CODE REVIEW

**Comment by kushniryb** [comment]
Hello @horgh, thank you for submitting this PR, much appreciated! 
It's quite large so it will take some time for me to review it but I'll try to do so in the upcoming days! 
Cheers!

**Comment by horgh** [comment]
Thank you! Yeah, it's large 😐. If there's anything I can do, please let me know!

**Comment by oschwald** [comment]
@kushniryb, is there a way we can help get this reviewed and merged sooner? MaxMind is trying to provide Ruby support for our services and we preferred updating and improving this API to creating our own as the code was of high quality and it already supported most of the necessary functionality. Thanks!

**Comment by kushniryb** [comment]
@oschwald 

Apologies for the delay, I'll get it sorted out by the end of this week. 

The issue with this PR is that it duplicates a lot of classes which are already defined as opposed to simply introducing the necessary changes.

I'll ping you once the necessary improvements are made.

**Comment by horgh** [comment]
Thank you! I'm happy to make changes. Which classes do you think we could do without?

In looking at it again, the thing that least thrills me is the stuff for backwards compatibility, e.g. https://github.com/kushniryb/minfraud-api-v2/pull/16/files#diff-84ac79e6b45d83dacfbbc292b96ef7a0R23-R56. But perhaps it's better than breaking things!

**Comment by kushniryb** [comment]
@horgh 
Could you please explain what is the purpose of `/models/*` classes considering we've got `/components/*`?

Example using `Device`, same goes for other payload elements.
 - https://github.com/kushniryb/minfraud-api-v2/blob/6a978c1b129f4f30f91efa073ae14a0c713289c6/lib/minfraud/model/device.rb
 - https://github.com/kushniryb/minfraud-api-v2/blob/master/lib/minfraud/components/device.rb

Would it be possible to simply add the necessary missing attributes to the `/components/*`?
Please correct me if I'm missing something important here.

**Comment by kushniryb** [comment]
@horgh 
You've mentioned that we need to introduce a dependency on GeoIP2
> However it adds a new dependency on maxmind-geoip2. This is because we can use the classes related to the GeoIP2 Insights response.

I'm going through documentation and it seems that it's related only to response body. Could you please explain what did you have in mind by stating that we could use classes related to GeoIP2? Is it done simply for convenience purposes in order to wrap the response? 

Also, could you please point me to the place where GeoIP2 is used in this PR?

I'm having some doubts as to whether this is necessary addition at the moment because I know for a fact that there are couple of projects using older Ruby versions < 2.4 in conjunction with this gem. We would have to introduce a deprecation warning first but that means that we would have to delay the merge of this PR for another couple of weeks. What are you thoughts on this subject? Do you feel like we could drop this dependency for now and devise a better way to tackle this problem?

**Comment by horgh** [comment]
Thanks for looking at it!

The `/models/*` classes are for the response objects. The `/components/*` classes are all about the request objects from what I could tell. For example, the API allows you to pass a [Device object](https://dev.maxmind.com/minfraud/#Device_(/device)) in the request, and then in the response there is a different [Device object](https://dev.maxmind.com/minfraud/#Device_(/device)-2). I thought it would be clearer to have different classes to represent these two things, given the properties in the response wouldn't make sense to pass as part of the request, and vice versa. There's also objects in both categories with different names (e.g. there's no `shipping_address` in the request). I'd be a little worried about adding the properties to the existing objects as it may become unclear about which can be in the request and which are in the response. Maybe we could namespace them differently or something? I'm not sure, but that's why I organized it this way!

**Comment by horgh** [comment]
Yes, the `maxmind-geoip2` dependency is so we can make use of that gem's classes for making objects for the GeoIP2 part of the response. The minFraud API [includes the GeoIP2](https://dev.maxmind.com/minfraud/#IP_Address_(/ipaddress)) response (with some additions), so depending on that gem saves us redefining all the classes from that API here. There's several objects involved.

We use the GeoIP2 class [here](https://github.com/kushniryb/minfraud-api-v2/pull/16/files#diff-84ac79e6b45d83dacfbbc292b96ef7a0R9) and [here](https://github.com/kushniryb/minfraud-api-v2/pull/16/files#diff-9c1fcac21706ee0698247b2eb9186285R8).

Yeah, it is unfortunate having to bump the Ruby version for this. Sorry about that! Do you have a sense about how far back we'd have to support? I know it's declared as 1.9+ right now, but maybe we could increase that a little, but not as much? One option would be for me to add support for older Rubys to `maxmind-geoip2` so we could keep the dependency, although 1.9 is pretty far back so I'm not sure how much work it would be.

Another option would be to copy over the relevant classes from `maxmind-geoip2` and avoid the dependency that way. It'll mean duplication with that gem and a bunch more classes here is one concern, but it might be okay for the time being. That might be the simplest way forward.

**Comment by kushniryb** [comment]
@horgh 

Thank you so much for your replies! 
Response classes make a lot of sense. I don't know why it was so hard for me to see that, apologies :) Thanks again for the detailed explanation! 

As for `maxmind-geoip2`, maybe we could try back-porting the changes that do not rely on the response classes to the current codebase, make a release so that it's compatible with Ruby < 2.4, merge your PR, make another release and maintain two separate versions at once. It could be potentially harder to maintain this gem in the future but I'm fine with making this sacrifice in favour of staying up to date and taking care of the customers that are relying on older versions of Ruby.

I'd like to spend tomorrow making some cosmetic changes to this PR.
I've promised to take care of this by the end of the previous week and I failed to deliver on that promise therefore I would like make those changes myself considering the difference in timezones. Would you be okay with me modifying your code a bit so that we could merge it tomorrow? We could discuss those changes afterwards and introduce an additional changes following your initiative where necessary. 

Lemme know what you think about it 🖖

**Comment by horgh** [comment]
Thanks for considering it :smile:. Don't worry about the promise!

Having two separate versions is interesting. Although it sounds painful maintenance wise as you say! I'm inclining towards copying the classes from the gem and dropping the dependency. I don't think it'll be that bad and it's probably easier long term. I'm happy to do that if you'd be okay with it!

Making any changes is fine with me though!

**Comment by horgh** [comment]
I decided to go for it! We can drop the commits if we change our minds.

I expect CI to fail as there's probably some newer Ruby features I used somewhere, but I'll fix it.

**Comment by horgh** [comment]
Looks like that did it! I'm done making changes for now, if you're still interested in making any changes as you mentioned. Please let me know if you see anything I can help with though!

**Comment by kushniryb** [comment]
Thank you so much for all the work, it looks great! ❤️
  
Merging it and will add slight changes in the follow-up PRs 🎉

**Comment by horgh** [comment]
Awesome, thank you! 😄

**Pull request merged**
